# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        in_memory:
            memory:
                users:
                    testuser:
                        password: testuser
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    
    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            
    firewalls:
 
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
        
            logout:
                path: /logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
                
    access_control:
        - { path: ^/search, roles: ROLE_USER }
        
